### ISSUE TITLE
TileEditor 1.3

### ISSUE THREAD

**Issue by mgiambrone** [huguesjohnson/MDLib#2]
I noticed Ardia 2.x is using TileEditor 1.3 but the version on this repo is 1.1
https://github.com/huguesjohnson/aridia wont compile with this dll, I get the following error:
F:\GitHub\aridia\Aridia 2.x\aridia\AridiaUI\MainForm.cs(7173,35,7173,49): error CS1729: 'TileEditorForm' does not contain a constructor that takes 6 arguments

**Comment by huguesjohnson** [comment]
Archiving this repo - closing open issues along the way. Sorry I didn't address this issue, this is not a project I've worked on for a while or plan to work on again.
